version: "3.3"
services:
  database:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - gateway
  web:
    image: top5radio-web
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - gateway
    depends_on:
      - api
  api:
    image: top5radio-api
    build:
      context: ./backend/Top5Radio.API/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - gateway
    depends_on:
      - database
  admin:
    image: top5radio-admin
    build:
      context: ./backend/Top5Radio.Admin/
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - gateway  
    depends_on:
      - database

networks:
  gateway: {}