version: "3.3"
services:
  database:
    image: mongo-express
    environment:
      MONGO_INITDB_ROOT_USERNAME: MongoDB
      MONGO_INITDB_ROOT_PASSWORD: example123    
    ports:
      - "8081:8081"
    networks:
      - gateway
  web:
    image: top5radio-web
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - gateway
  api:
    image: top5radio-api
    build:
      context: ./backend/Top5Radio.API/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - gateway
  admin:
    image: top5radio-admin
    build:
      context: ./backend/Top5Radio.Admin/
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - gateway  

networks:
  gateway: {}