version: "3.3"
services:
  web:
    image: top5radio-web
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
  api:
    image: top5radio-api
    build:
      context: ./backend/Top5Radio.API/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  admin:
    image: top5radio-admin
    build:
      context: ./backend/Top5Radio.Admin/
      dockerfile: Dockerfile
    ports:
      - "5001:80"